jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  bootConfigURL: https://github.com/jenkins-x/jx3-boot-config
  buildPacks:
    buildPackLibrary:
      gitRef: master
      gitURL: https://github.com/jenkins-x/jx3-pipeline-catalog.git
  cluster:
    clusterName: tf-jx-fleet-hermit
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "291005901394"
    namespace: jx
    project: camunda-researchanddevelopment
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: dev
    owner: salaboy
    repository: jx3-cluster
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: staging
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: production
  gitops: true
  ingress:
    domain: 35.223.222.15.nip.io
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kaniko: true
  pipelineUser:
    username: salaboy
  repository: nexus
  secretStorage: gsm
  storage:
    backup:
      enabled: false
      url: ""
    logs:
      enabled: true
      url: gs://logs-tf-jx-fleet-hermit-3cd24e4144db
    reports:
      enabled: true
      url: gs://reports-tf-jx-fleet-hermit-3cd24e4144db
    repository:
      enabled: true
      url: gs://repository-tf-jx-fleet-hermit-3cd24e4144db
  vault: {}
  velero:
    schedule: ""
    ttl: ""
  versionStream:
    ref: master
    url: https://github.com/jenkins-x/jxr-versions.git
  webhook: lighthouse
